### ISSUE TITLE
npm run build fail

### ISSUE THREAD

**Issue by yrong** [pietrzakadrian/bank-client#1]
```
ERROR in ./app/images/icon.png
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: Cannot find module 'gifsicle'
Require stack:
- /Users/ronyang/Dev/mynode/bank/client/node_modules/imagemin-gifsicle/index.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/image-webpack-loader/index.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/loader-runner/lib/loadLoader.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack/lib/NormalModule.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack/lib/Compiler.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack/lib/webpack.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack-cli/bin/utils/validate-options.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack-cli/bin/utils/convert-argv.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack-cli/bin/cli.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (/Users/ronyang/Dev/mynode/bank/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/ronyang/Dev/mynode/bank/client/node_modules/imagemin-gifsicle/index.js:3:18)
    at Module._compile (/Users/ronyang/Dev/mynode/bank/client/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Module._compile (/Users/ronyang/Dev/mynode/bank/client/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.newLoader [as .js] (/Users/ronyang/Dev/mynode/bank/client/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (/Users/ronyang/Dev/mynode/bank/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.module.exports (/Users/ronyang/Dev/mynode/bank/client/node_modules/image-webpack-loader/index.js:66:20)
 @ ./app/components/App/Mark/index.js 11:0-35 17:7-11
 @ ./app/components/App/Header/index.js
 @ ./app/components/App/Layout/index.js
 @ ./app/containers/App/index.js
 @ ./app/app.js

ERROR in ./app/images/logo.png
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: Cannot find module 'gifsicle'
Require stack:
- /Users/ronyang/Dev/mynode/bank/client/node_modules/imagemin-gifsicle/index.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/image-webpack-loader/index.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/loader-runner/lib/loadLoader.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack/lib/NormalModule.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack/lib/Compiler.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack/lib/webpack.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack-cli/bin/utils/validate-options.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack-cli/bin/utils/convert-argv.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack-cli/bin/cli.js
- /Users/ronyang/Dev/mynode/bank/client/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (/Users/ronyang/Dev/mynode/bank/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/ronyang/Dev/mynode/bank/client/node_modules/imagemin-gifsicle/index.js:3:18)
    at Module._compile (/Users/ronyang/Dev/mynode/bank/client/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Module._compile (/Users/ronyang/Dev/mynode/bank/client/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.newLoader [as .js] (/Users/ronyang/Dev/mynode/bank/client/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (/Users/ronyang/Dev/mynode/bank/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.module.exports (/Users/ronyang/Dev/mynode/bank/client/node_modules/image-webpack-loader/index.js:66:20)
 @ ./app/components/App/Logo/index.js 11:0-35 17:7-11
 @ ./app/components/App/Drawer/index.js
 @ ./app/components/App/Layout/index.js
 @ ./app/containers/App/index.js
 @ ./app/app.js
```

**Comment by pietrzakadrian** [comment]
Try:
`yarn && yarn build`

**Comment by yrong** [comment]
resolve after remove image-webpack-loader
![image](https://user-images.githubusercontent.com/4383920/91301950-4b453380-e7d8-11ea-927d-cab947a9c9fa.png)
